var nameList = [
    'Time','Aman','Ayush','Swarna',
    "Aarav", "Vivaan", "Aditya", "Kabir", "Arjun", "Rohan", "Kunal", "Raj", "Pranav", "Dev",
    "Ishaan", "Yash", "Ritik", "Samar", "Harsh", "Siddharth", "Neel", "Kartik", "Reyansh", "Vikram",
    "Vedant", "Ayan", "Manav", "Tejas", "Atharv", "Rudra", "Shaurya", "Abhinav", "Gautam", "Aniket",
    "Omkar", "Raghav", "Sandeep", "Ujjwal", "Dhruv", "Vishal", "Nikhil", "Soham", "Chetan", "Niraj",
    "Tushar", "Jayant", "Rajat", "Bhaskar", "Eshan", "Harshit", "Devansh", "Hemant", "Lokesh", "Arvind",
    "Shivam", "Yuvraj", "Keshav", "Rakesh", "Vimal", "Jitendra", "Sunil", "Anmol", "Bharat", "Madhav",
    "Sharad", "Dinesh", "Rajeev", "Ramesh", "Venkatesh", "Suraj", "Abhishek", "Lakshman", "Akhil", "Uday",
    "Ravindra", "Vijay", "Ganesh", "Ashwin", "Parth", "Shashank", "Ravi", "Mohan", "Prakash", "Amit",
    "Praveen", "Kiran", "Naveen", "Sachin", "Sagar", "Ajay", "Rohit", "Mayank", "Chirag", "Bhavesh",
    "Ananya", "Aarohi", "Saanvi", "Ishita", "Diya", "Kiara", "Meera", "Riya", "Shruti", "Avni",
    "Pooja", "Jhanvi", "Simran", "Trisha", "Suhani", "Navya", "Tanya", "Sanya", "Aisha", "Priya",
    "Sneha", "Harini", "Tanvi", "Bhavya", "Swara", "Mira", "Nandini", "Sakshi", "Lavanya", "Muskan",
    "Vidhi", "Rupal", "Roshni", "Neha", "Payal", "Parvati", "Varsha", "Aditi", "Madhuri", "Charu",
    "Komal", "Kavita", "Supriya", "Deepika", "Nikita", "Ruchi", "Sonal", "Pallavi", "Radhika", "Chitra",
    "Himani", "Anjali", "Gargi", "Seema", "Asmita", "Manisha", "Geetanjali", "Priyanka", "Bhavana", "Rajeshwari",
    "Savita", "Leena", "Amruta", "Megha", "Suman", "Jaya", "Shweta", "Kirti", "Mamta", "Malini",
    "Divya", "Anushka", "Ira", "Jasmine", "Mahima", "Rupali", "Sarita", "Urmila", "Vaishnavi", "Yamini",
    'Zombie','Sarge','Capt','Captain','Punch','One','Two','Uno','Slice',
    'Slash','Melt','Melted','Melting','Fell','Wolf','Hound',
    'Legacy','Sharp','Dead','Mew','Chuckle','Bubba','Bubble','Sandwich', "Arvind", "Venkatesh", "Sridhar", "Raghavan", "Bala", "Ramesh", "Sundar", "Mahesh", "Ganesh", "Shankar",
    "Prakash", "Madhavan", "Lakshman", "Kannan", "Karthik", "Harish", "Vijayan", "Surya", "Ravindra", "Kumar",
    "Gopal", "Anand", "Rajan", "Subramanian", "Jayakumar", "Krishna", "Narayan", "Chandran", "Manoj", "Sathish",
    "Deepak", "Shiva", "Dhanush", "Arun", "Jayesh", "Balaji", "Venkat", "Hari", "Vishnu", "Naveen",
    "Aishwarya", "Bhavani", "Charulatha", "Deepa", "Esha", "Gayathri", "Hema", "Indira", "Janaki", "Kavya",
    "Lalitha", "Meena", "Nalini", "Oviya", "Priyanka", "Radha", "Sangeeta", "Trisha", "Uma", "Vidya",
    "Vaishnavi", "Swapna", "Sharvani", "Roshini", "Pavitra", "Malini", "Jyothika", "Iswarya", "Indumathi", "Harini",
    "Anirban", "Arka", "Bikram", "Debashish", "Gourav", "Himanshu", "Indrajit", "Joy", "Kaustav", "Lalit",
    "Madhusudan", "Nirupam", "Partha", "Rajib", "Subhajit", "Tamal", "Uttam", "Vikash", "Anupam", "Barun",
    "Chirantan", "Dipankar", "Gautam", "Kalyan", "Lokesh", "Manas", "Nanda", "Omkara", "Prabir", "Ritwik",
    "Anupama", "Brishti", "Chaitali", "Debolina", "Esha", "Farha", "Geetanjali", "Hiranmayi", "Ipshita", "Jaya",
    "Kasturi", "Lopamudra", "Madhumita", "Nabanita", "Oindrila", "Paromita", "Ritika", "Sudeshna", "Tiyasha", "Uma",
    "Bhaskar", "Chintan", "Deepesh", "Eknath", "Feroz", "Girish", "Harshal", "Indrajit", "Jayendra", "Kishore",
    "Lalit", "Mahendra", "Nikhil", "Omprakash", "Pritesh", "Rajendra", "Santosh", "Tushar", "Umesh", "Viral",
    "Amruta", "Bhavna", "Chandni", "Deepika", "Ekta", "Farheen", "Gargi", "Heena", "Indrani", "Jalpa",
    "Kalpana", "Leena", "Madhavi", "Namrata", "Ojaswini", "Pooja", "Rupali", "Snehal", "Trupti", "Vaishali"
];

const Messages = [
   "Hello! What's up?",
    "Life is too short for bad vibes! ✨",
    "Keep pushing forward, you're doing great! 🚀",
    "What's your go-to comfort food?",
    "Coding all day or chilling all night? 💻🌙",
    "If you could have any superpower, what would it be? 🦸‍♂️",
    "What song are you listening to these days? ",
    "If you were in a video game, which one would it be? 🎮",
    "A random fact about you? 🤔",
    "Coffee or Tea? ☕🍵",
    "The best way to start a day is with a smile! 😃",
    "Have you ever tried learning a new language? ",
    "Mountains or beaches? ",
    "Happiness is in the little things! 🌸",
    "What was your childhood dream job? 🚀",
    "Pineapple on pizza? Yes or No?",
    "What's the best book you've ever read? 📖",
    "Do you believe in fate or free will? 🔮",
    "What's one skill you wish you had? 🎨",
    "If you could time travel, where would you go? ⏳",
    "What's your guilty pleasure? 😆",
    "Pizza or burger? ",
    "Dogs or cats? ",
    "What's your favorite dessert? 🍨",
    "If you had to live in a movie, which one would it be? 🎬",
    "Night owl or early bird? 🌙☀️",
    "Have you ever tried skydiving? 🪂",
    "If you had a pet dragon, what would you name it? 🐉",
    "Would you rather be invisible or read minds? 🤯",
    "What's your go-to comfort TV show? 📺",
    "What's one thing you can't live without? ❤️",
    "Would you rather travel to space or the deep sea? 🚀🌊",
    "What's your biggest fear? 😨",
    "What's your dream travel destination? ✈️",
    "What's your weirdest talent? 🤹",
    "What's the last thing that made you laugh? 😂",
    "If you could be any fictional character, who would you be? 📚",
    "What's the funniest joke you know? 😆",
    "Would you rather have a rewind or pause button for life? ⏳",
    "If you could relive one day, which one would it be? 🔄",
    "Would you rather be super rich or super famous? 💰",
    "What's a secret talent you have? 🎭",
    "What's your go-to karaoke song? 🎤",
    "What's your most-used emoji? 🤔",
    "What's one thing that instantly makes your day better? ☀️",
    "If you had a theme song, what would it be? 🎶",
    "What's the best piece of advice you've ever received? 💡",
    "What's one thing you regret not doing? 🤷",
    "What's something you've always wanted to learn? 📚",
    "कैसे हो? 😃",
    "Life is too short to worry. Just smile and move on! 😊",
    "Somewhere, someone is having their best day. Why not you? 🌟",
    "Pizza solves most problems. Change my mind! ",
    "Mondays should come with a fast-forward button. ⏩",
    "Good vibes only! Keep shining! ✨",
    "If coffee had a face, I'd marry it.",
    "You're one decision away from changing your life! 🚀",
    "The universe is big, but your potential is bigger. 🌌",
    "If your dreams don’t scare you, they aren’t big enough. 💭",
    "Dance like no one is watching, but check for cameras first! ",
    "Chocolate makes everything better. Fact! 🍫",
    "A moment of patience can prevent a lifetime of regret. 🙌",
    "The best stories begin with ‘Remember that time when…’ 🤭",
    "Lazy day? No problem. Even a sloth gets where it wants! 🦥",
    "If I had a rupee for every bad joke I made, I’d be rich! ",
    "Adventure is out there! Are you ready? 🌍",
    "Kindness is free. Sprinkle it everywhere! ❤️",
    "Sunsets are proof that endings can be beautiful too. 🌅",
    "Running late is my cardio.",
    "The secret to happiness? Ice cream. 🍦",
    "Happiness is homemade... and sometimes delivered by Zomato! 🍕",
    "If you love what you do, Mondays don’t exist! 🏆",
    "Mistakes are proof you are trying. Keep going! 🔥",
    "Stop scrolling. Take a deep breath. Relax. 😊",
    "There’s nothing a power nap can’t fix. 💤",
    "Who needs a superhero when you have WiFi? ",
    "What’s a day without a little adventure? 🌄",
    "Your dreams won’t work unless you do! 💪",
    "Laughter is the best exercise. So keep laughing! 😆",
    "A goal without a plan is just a wish! 🎯",
    "Turn the page. Your next chapter is waiting.",
    "A little progress each day adds up to big results! 📈",
    "Why walk when you can dance?",
    "Every morning is a fresh start! ",
    "Don’t be busy, be productive. ⏳",
    "Dream big, work hard, stay focused! 🎯",
    "No rain, no flowers.",
    "Take it easy. Stress is just a mind game! ",
    "आज कुछ मजेदार करते हैं! 🎉",
    "ज़िंदगी छोटी है, इसे खुलकर जियो! 😊",
    "चाय के बिना सुबह अधूरी लगती है! ☕",
    "तुम्हारा फेवरेट बॉलीवुड मूवी कौन सा है? ",
    "क्या तुम कभी किसी भूतिया जगह गए हो? 👻",
    "घर का खाना सबसे बेस्ट होता है! 🍛",
    "आज मौसम बहुत सुहाना है, घूमने चले? 🌦️",
    "दिल से खुश रहो, सब बढ़िया रहेगा! ❤️",
    "तुम्हें किस तरह की म्यूजिक पसंद है? ",
    "अगर टाइम मशीन होती, तो तुम कहाँ जाते?",
    "बचपन की सबसे यादगार शरारत क्या थी? ",
    "गोलगप्पे या मोमोज़? 🤤",
    "आज की दुनिया में बिना इंटरनेट रह सकते हो? 🌐",
    "खुश रहो, मुस्कुराते रहो! 😊",
    "कोई सपना जो तुम पूरा करना चाहते हो? ",
    "अगर तुम सुपरहीरो होते, तो नाम क्या होता? ",
    "क्या तुमने कभी ट्रेन की छत पर सफर किया है? 🚂",
    "खाने में सबसे ज्यादा क्या पसंद है? 🍽️",
    "शाहरुख़ खान या सलमान खान? 🎥",
    "क्या तुमने कभी किसी को प्रैंक किया है? 😆",
    "सपने देखना अच्छी बात है, पर मेहनत जरूरी है! 💪",
    "तुम्हारी सबसे फनी याद कौन सी है? 😂",
    "पहाड़ों की ठंडी हवा या समंदर का शोर?",
    "माँ के हाथ का खाना सबसे अच्छा होता है! 🍛",
    "रात में तारे देखना पसंद है? ✨",
    "अगर तुम्हें जादू की शक्ति मिल जाए, तो क्या करोगे?",
    "कॉमेडी शो देखना पसंद है? 😂",
    "क्या तुम भूतों पर विश्वास करते हो? 👻",
    "आज का दिन कैसा रहा? 🌞",
    "सच्चे दोस्त बहुत कीमती होते हैं! ❤️",
    "अगर तुम्हें कोई एक दिन के लिए राजा बना दे, तो क्या करोगे? 👑",
    "अगर कोई जादुई जिन्न मिले, तो कौन सी तीन इच्छाएँ मांगोगे? 🧞‍♂️",
    "बचपन में सबसे ज्यादा क्या पसंद था? ",
    "गर्मा-गर्म समोसे और चाय, क्या बात है! ☕",
    "कभी मेट्रो में सफर किया है? 🚇",
    "खाने में सबसे ज्यादा क्या पसंद है? 🍽️",
    "ज़िन्दगी बहुत छोटी है, इसे हंसते-खेलते बिताओ! 😃",
    "समस्या चाहे कितनी भी बड़ी हो, चाय और गप्पें सब ठीक कर देती हैं! ☕",
    "हर दिन नया मौका है, कुछ नया करने का! 🚀",
    "पेट भर जाने के बाद ही पता चलता है कि खाना कितना अच्छा था! 🍛",
    "अगर आलस से कुछ मिलता, तो मैं सबसे अमीर इंसान होता! ",
    "बचपन की सबसे अच्छी बात थी—टेंशन फ्री ज़िन्दगी! 🎈",
    "मुश्किलें भी कुछ सिखाने आती हैं, सीखो और आगे बढ़ो! 💪",
    "कभी-कभी चुप रहना सबसे बड़ा जवाब होता है! 🤫",
    "हंसते रहो, हंसाने वालों की कमी नहीं है! 😆",
    "कुछ लोग सलाह देने में PhD किए होते हैं! ",
    "चाय और दोस्त, दोनों पुराने होने चाहिए! ☕",
    "मुश्किलें आती हैं, पर ज़िन्दगी रुकती नहीं! 🔥",
    "खुश रहो, टेंशन में तो सब रहते हैं! 😄",
    "बड़ा सपना देखो, बड़ा काम करो! 🏆",
    "घर का खाना और माँ की डांट, दोनों में प्यार छिपा होता है! ❤️",
    "जब दिल खुश होता है, तो दुनिया भी खूबसूरत लगती है! 🌍",
    "अगर आलस ओलंपिक में खेल होता, तो हम गोल्ड जीत जाते!",
    "खाना गरम और दोस्त सच्चे मिलने मुश्किल हैं! 😆",
    "मोटिवेशन चाहिए? माँ से बोलो, 'मैं कुछ नहीं कर सकता!' 🤯",
    "छोटी-छोटी खुशियों का मजा लेना सीखो, ज़िन्दगी खूबसूरत लगेगी! ❤️",
    "बच्चे के हाथ में चॉकलेट और बड़ों के हाथ में फोन—कभी नहीं टिकता!",
    "कामयाबी मेहनत से मिलती है, शॉर्टकट से नहीं! 🔥",
    "किस्मत का लिखा भी तभी मिलता है, जब मेहनत का रंग चढ़ता है! 💪",
    "खुश रहोगे, तो दुनिया भी अच्छी लगेगी! 😃",
    "मुश्किलों से लड़ो, क्योंकि हारने वाले को कोई याद नहीं रखता! 🎯",
    "हर दिन कुछ नया सीखने का मौका है! 📚",
    "सोच बदलो, दुनिया खुद बदल जाएगी! 🌏",
    "आज कुछ अच्छा करो, कल खुद पर गर्व होगा! 😍",
    "कभी-कभी खुद को भी खुश करने के लिए जीना चाहिए! 😊",
    "सफलता पाने का सबसे आसान तरीका—शुरुआत करना! 🚀",
    "ज़िन्दगी का मजा लेना है, तो हंसते रहो! 😆",
    "माँ की दुआ और पिता की मेहनत से बड़ा कोई आशीर्वाद नहीं! 🙏",
    "बुरी आदतों से दूर रहो, और अच्छी संगत को अपनाओ! 😇",
    "जो होना है, वो होकर रहेगा, चिंता मत करो! 🌸",
];



export function getRandomhMessage() {
    return Messages[Math.floor(Math.random() * Messages.length)];
}

export function generator() {
   return nameList[Math.floor( Math.random() * nameList.length )];
};